# 
# GenerateGreatCourseGenerateJS.py
#
# load in JSON file created by GenerateGreatCourseURLs.py, and generate a simple .JS file
# for use with our Chrome plugin 
# 
# Benjamin Pritchard / Kundalini Software
#
# 23-March-2018     Version 1.0     Initial Release
#


import json

code_header = '''// this lookup table is auto-generated by GenerateGreatCourseGenerateJS.py
// Any modifications to this file will be lost if you run the script again!!
var lookup = new Map([ 
'''

code_footer = ''']);
// find out name of current course...
courseTitle = document.getElementsByClassName("course-info")[0].firstElementChild.innerText;
console.log("course title = " + courseTitle);

// lookup its URL...
URL = lookup.get(courseTitle);
console.log("URL = " + URL);

// and add a new button to it...
if (URL != undefined) {
ButtonContainer=document.getElementsByClassName("button-container");
NewHTML = "<p> <form target='_blank'><button formaction=" + URL + ">Great Courses</button></form>";
ButtonContainer[0].innerHTML = ButtonContainer[0].innerHTML + NewHTML; 
}
'''

print("Reading and parsing course JSON...")
# grab the course data from disk...
with open('courseOutput.JSON') as json_file:  
    data = json.load(json_file)

print("Creating Javascript...")
with open('greatcourses.js', 'w') as output_js_file:
    output_js_file.write(code_header)

    counter = 0
    for course in data:

        if counter == (len(data) - 1):      # don't put a comma on the last line!!
           CommaString = ""
        else:
            CommaString = ","    

        output_js_file.write(
            '["%s","%s"]%s\n' % (course["COURSE_TITLE"], course["GREATCOURSEURL"], CommaString))

        counter += 1

    output_js_file.write(code_footer)

print("Done")

